make -C ../../../bootloader BOARD=PAPILIO_ONE SIZE=16384 DEFINES="-D__S3E_250__ -DBOARD_ID=0xA4020E00 -DBOARD_MEMORYSIZE=0x4000"
make[1]: Entering directory `/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/bootloader'
zpu-elf-g++ -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_PAPILIO_ONE__  -D__S3E_250__ -DBOARD_ID=0xA4020E00 -DBOARD_MEMORYSIZE=0x4000 -fno-exceptions   -c -o boot.o boot.cpp
zpu-elf-gcc -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_PAPILIO_ONE__  -D__S3E_250__ -DBOARD_ID=0xA4020E00 -DBOARD_MEMORYSIZE=0x4000   -c -o boot-c.o boot-c.c
zpu-elf-gcc -D__ZPUINO_PAPILIO_ONE__ -D__S3E_250__ -DBOARD_ID=0xA4020E00 -DBOARD_MEMORYSIZE=0x4000 -DASSEMBLY -I../common   -c -o boot-s.o boot-s.S
zpu-elf-g++ boot.o boot-c.o boot-s.o -o bootloader.elf -O2 -Wl,-T -Wl,zpuelf.lds -Wl,--relax -Wl,--gc-sections 
zpu-elf-objdump -D bootloader.elf > bootloader.s
zpu-elf-objcopy -O binary bootloader.elf bootloader.bin
zpu-elf-objcopy -O ihex bootloader.elf bootloader.hex
perl ../gen-prom-generic-dualport_32.pl bootloader.bin 16384 > prom-generic-dp-32.vhd || rm -f prom-generic-dp-32.vhd	
zpu-elf-g++ -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_PAPILIO_ONE__  -D__S3E_250__ -DBOARD_ID=0xA4020E00 -DBOARD_MEMORYSIZE=0x4000 -fno-exceptions -S boot.cpp -o bootloader.S
make[1]: Leaving directory `/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/bootloader'
cp ../../../bootloader/prom-generic-dp-32.vhd .
mkdir -p xst/projnav.tmp/
xst -intstyle ise -ifn papilio_one.xst -ofn papilio_one.syr
Reading design: papilio_one.prj

=========================================================================
*                          HDL Compilation                              *
=========================================================================
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/papilio_one/s3e250/zpu_config.vhd" in Library work.
Package <zpu_config> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpupkg.vhd" in Library work.
Package <zpupkg> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/papilio_one/s3e250/zpuino_config.vhd" in Library work.
Package <zpuino_config> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuinopkg.vhd" in Library work.
Package <zpuinopkg> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/papilio_one/s3e250/prom-generic-dp-32.vhd" in Library work.
Entity <prom_generic_dualport> compiled.
Entity <prom_generic_dualport> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/prescaler.vhd" in Library work.
Entity <prescaler> compiled.
Entity <prescaler> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_uart_mv_filter.vhd" in Library work.
Entity <zpuino_uart_mv_filter> compiled.
Entity <zpuino_uart_mv_filter> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/uart_brgen.vhd" in Library work.
Entity <uart_brgen> compiled.
Entity <uart_brgen> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_intr.vhd" in Library work.
Entity <zpuino_intr> compiled.
ERROR:HDLParsers:3312 - "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_intr.vhd" Line 194. Undefined symbol 'Undefined'.
--> 


Total memory usage is 165536 kilobytes

Number of errors   :    1 (   0 filtered)
Number of warnings :    0 (   0 filtered)
Number of infos    :    0 (   0 filtered)

