make -C ../../../bootloader BOARD=NEXYS2 SIZE=32768 DEFINES="-DBOARD_ID=0x84010F00 -DBOARD_MEMORYSIZE=0x8000"
make[1]: Entering directory `/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/bootloader'
zpu-elf-g++ -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_NEXYS2__  -DBOARD_ID=0x84010F00 -DBOARD_MEMORYSIZE=0x8000 -fno-exceptions   -c -o boot.o boot.cpp
zpu-elf-gcc -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_NEXYS2__  -DBOARD_ID=0x84010F00 -DBOARD_MEMORYSIZE=0x8000   -c -o boot-c.o boot-c.c
zpu-elf-gcc    -c -o boot-s.o boot-s.S
zpu-elf-g++ boot.o boot-c.o boot-s.o -o bootloader.elf -O2 -Wl,-T -Wl,zpuelf.lds -Wl,--relax -Wl,--gc-sections 
zpu-elf-objdump -D bootloader.elf > bootloader.s
zpu-elf-objcopy -O binary bootloader.elf bootloader.bin
zpu-elf-objcopy -O ihex bootloader.elf bootloader.hex
perl ../gen-prom-generic-dualport_32.pl bootloader.bin 32768 > prom-generic-dp-32.vhd || rm -f prom-generic-dp-32.vhd	
zpu-elf-g++ -O2 -fno-gcse -Wall -mno-callpcrel  -fdata-sections -ffunction-sections -I../common -D__ZPUINO_NEXYS2__  -DBOARD_ID=0x84010F00 -DBOARD_MEMORYSIZE=0x8000 -fno-exceptions -S boot.cpp -o bootloader.S
make[1]: Leaving directory `/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/bootloader'
cp ../../../bootloader/prom-generic-dp-32.vhd ./rtl/
mkdir -p xst/projnav.tmp/
xst -intstyle ise -ifn nexys2_zpuino.xst -ofn nexys2_zpuino.syr
Reading design: nexys2_zpuino.prj

=========================================================================
*                          HDL Compilation                              *
=========================================================================
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/nexys2/s3e1200/rtl/zpu_config.vhd" in Library work.
Package <zpu_config> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpupkg.vhd" in Library work.
Package <zpupkg> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/nexys2/s3e1200/rtl/zpuino_config.vhd" in Library work.
Package <zpuino_config> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuinopkg.vhd" in Library work.
Package <zpuinopkg> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/boards/nexys2/s3e1200/rtl/prom-generic-dp-32.vhd" in Library work.
Entity <prom_generic_dualport> compiled.
Entity <prom_generic_dualport> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/prescaler.vhd" in Library work.
Entity <prescaler> compiled.
Entity <prescaler> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_uart_mv_filter.vhd" in Library work.
Entity <zpuino_uart_mv_filter> compiled.
Entity <zpuino_uart_mv_filter> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/uart_brgen.vhd" in Library work.
Entity <uart_brgen> compiled.
Entity <uart_brgen> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_intr.vhd" in Library work.
Entity <zpuino_intr> compiled.
Entity <zpuino_intr> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/wishbonepkg.vhd" in Library work.
Package <wishbonepkg> compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/dualport_ram.vhd" in Library work.
Entity <dualport_ram> compiled.
Entity <dualport_ram> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/shifter.vhd" in Library work.
Entity <lshifter> compiled.
Entity <lshifter> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/timer.vhd" in Library work.
Entity <timer> compiled.
Entity <timer> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpuino_uart_rx.vhd" in Library work.
Entity <zpuino_uart_rx> compiled.
Entity <zpuino_uart_rx> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/tx_unit.vhd" in Library work.
Entity <TxUnit> compiled.
Entity <TxUnit> (Architecture <Behaviour>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/fifo.vhd" in Library work.
Entity <fifo> compiled.
Entity <fifo> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/spi.vhd" in Library work.
Entity <spi> compiled.
Entity <spi> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/spiclkgen.vhd" in Library work.
Entity <spiclkgen> compiled.
Entity <spiclkgen> (Architecture <behave>) compiled.
Compiling vhdl file "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpu_core_extreme.vhd" in Library work.
Entity <zpu_core_extreme> compiled.
ERROR:HDLParsers:3312 - "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpu_core_extreme.vhd" Line 570. Undefined symbol 'enable_fmul16'.
ERROR:HDLParsers:1209 - "/mnt/scratch/ZPUino-HDL/zpu/hdl/zpuino/zpu_core_extreme.vhd" Line 570. enable_fmul16: Undefined symbol (last report in this block)
--> 


Total memory usage is 172148 kilobytes

Number of errors   :    2 (   0 filtered)
Number of warnings :    0 (   0 filtered)
Number of infos    :    0 (   0 filtered)

